language: node_js
node_js:
  - 10.16.0
  - node
dist: xenial
sudo: required

branches:
  only:
    - develop

script:
  - npm run test
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  target-branch: master
  on:
    branch: develop