language: node_js
node_js:
  - 14.15.4
  - node
dist: bionic
sudo: required

env:
  CI: false

branches:
  only:
    - develop

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  on:
    branch: develop
    node: 14.15.4
  target_branch: master
  local_dir: build
  fqdn: cconverter.codrill.eu
